from __future__ import annotations

import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import osmnx as ox


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "data" / "neighborhoods.json"
DEFAULT_RADIUS_M = 1200


NEIGHBORHOODS = [
    {
        "name": "Navy Yard",
        "lat": 38.8765,
        "lon": -77.0059,
        "radius_m": DEFAULT_RADIUS_M,
        "summary": "Modern waterfront area with newer buildings, a lively restaurant scene, and strong appeal for young professionals.",
        "rent_1br": 2925,
        "rent_2br": 4625,
        "rent_3br": 6180,
    },
    {
        "name": "NoMa",
        "lat": 38.9066,
        "lon": -77.0033,
        "radius_m": DEFAULT_RADIUS_M,
        "summary": "Fast-growing and apartment-heavy with strong Metro access, coworking energy, and lots of casual food options.",
        "rent_1br": 2650,
        "rent_2br": 4225,
        "rent_3br": 5640,
    },
    {
        "name": "Foggy Bottom",
        "lat": 38.9007,
        "lon": -77.0502,
        "radius_m": DEFAULT_RADIUS_M,
        "summary": "Central and practical with easy downtown access, Metro convenience, and a quieter feel than the nightlife-heavy areas.",
        "rent_1br": 2875,
        "rent_2br": 4510,
        "rent_3br": 5970,
    },
    {
        "name": "Adams Morgan",
        "lat": 38.9227,
        "lon": -77.0424,
        "radius_m": DEFAULT_RADIUS_M,
        "summary": "Social, energetic, and nightlife-focused with dense dining options and a strong weekend scene.",
        "rent_1br": 2475,
        "rent_2br": 3940,
        "rent_3br": 5310,
    },
    {
        "name": "Arlington",
        "lat": 38.8816,
        "lon": -77.0910,
        "radius_m": 1400,
        "summary": "Clean, structured, and consistently popular with post-grad professionals who want convenience and a slightly calmer feel.",
        "rent_1br": 2525,
        "rent_2br": 4040,
        "rent_3br": 5460,
    },
    {
        "name": "Ballston",
        "lat": 38.8814,
        "lon": -77.1113,
        "radius_m": DEFAULT_RADIUS_M,
        "summary": "A growing Arlington hub with modern buildings, strong Metro access, and an easy balance of convenience and nightlife.",
        "rent_1br": 2450,
        "rent_2br": 3890,
        "rent_3br": 5220,
    },
    {
        "name": "Dupont Circle",
        "lat": 38.9096,
        "lon": -77.0434,
        "radius_m": DEFAULT_RADIUS_M,
        "summary": "Central, polished, and highly walkable with strong dining options, classic DC housing stock, and convenient access across the city.",
        "rent_1br": 3050,
        "rent_2br": 4825,
        "rent_3br": 6480,
    },
]


METRIC_TAGS = {
    "food_density": {
        "amenity": [
            "restaurant",
            "fast_food",
            "cafe",
            "bar",
            "pub",
            "food_court",
            "biergarten",
        ]
    },
    "nightlife_density": {"amenity": ["bar", "pub", "nightclub"]},
    "grocery_density": {"shop": ["supermarket", "convenience"]},
    "green_density": {"leisure": ["park", "garden"]},
    "transit_density": {
        "public_transport": True,
        "railway": ["station", "subway_entrance", "halt", "tram_stop"],
        "station": ["subway"],
        "amenity": ["bus_station"],
    },
}


def fetch_feature_count(lat: float, lon: float, radius_m: int, tags: dict[str, Any]) -> int:
    features = ox.features_from_point((lat, lon), tags=tags, dist=radius_m)
    if features.empty:
        return 0
    return int(features.index.nunique())


def density_from_count(count: int, radius_m: int) -> float:
    area_sq_km = math.pi * (radius_m**2) / 1_000_000
    return round(count / area_sq_km, 1)


def build_record(neighborhood: dict[str, Any]) -> dict[str, Any]:
    metrics = {}
    for metric_name, tags in METRIC_TAGS.items():
        count = fetch_feature_count(
            neighborhood["lat"],
            neighborhood["lon"],
            neighborhood["radius_m"],
            tags,
        )
        metrics[metric_name] = density_from_count(count, neighborhood["radius_m"])

    return {
        "name": neighborhood["name"],
        "lat": neighborhood["lat"],
        "lon": neighborhood["lon"],
        "radius_m": neighborhood["radius_m"],
        "summary": neighborhood["summary"],
        "rent_1br": neighborhood["rent_1br"],
        "rent_2br": neighborhood["rent_2br"],
        "rent_3br": neighborhood["rent_3br"],
        "metrics": metrics,
    }


def main() -> None:
    ox.settings.use_cache = True
    ox.settings.log_console = True

    records = [build_record(neighborhood) for neighborhood in NEIGHBORHOODS]
    now = datetime.now(timezone.utc)
    payload = {
        "last_updated": now.replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "last_updated_label": now.strftime("%B %d, %Y"),
        "update_note": "OpenStreetMap metrics can be regenerated by workflow. Rent values are still curated estimates and should be reviewed before high-stakes use.",
        "neighborhoods": records,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {len(records)} neighborhoods to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
